version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - C:/Backup/Docker/nextcloud-db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud!@
      - MYSQL_PASSWORD=nextcloud!@
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    container_name: nextcloud
    ports:
      - 15000:80
    links:
      - db
    volumes:
      - ./config:/var/www/html/config
      - C:/Backup/Docker/nextcloud/apps:/var/www/html/custom_apps
      - C:/Backup/Docker/nextcloud/data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=nextcloud!@
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db